version: '3.8'

services:
  memgos:
    build: .
    container_name: memgos-api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - MEMGOS_LOG_LEVEL=info
      - MEMGOS_API_PORT=8080
      - NATS_URL=nats://nats:4222
    depends_on:
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - memgos-network

  memgos-mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: memgos-mcp
    depends_on:
      memgos:
        condition: service_healthy
    environment:
      - MEMGOS_API_TOKEN=${MEMGOS_API_TOKEN}
      - MEMGOS_API_URL=http://memgos:8080
      - MEMGOS_USER_ID=default-user
      - MEMGOS_SESSION_ID=mcp-session
      - NATS_URL=nats://nats:4222
    volumes:
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    networks:
      - memgos-network

  # NATS server for messaging and key-value store
  nats:
    image: nats:2.10-alpine
    container_name: memgos-nats
    ports:
      - "4222:4222"    # NATS client connections
      - "8222:8222"    # HTTP monitoring
      - "6222:6222"    # Clustering
    command: >
      --jetstream
      --store_dir=/data
      --http_port=8222
      --cluster_name=memgos-cluster
      --cluster=nats://0.0.0.0:6222
      --max_file_store=1GB
      --max_mem_store=256MB
    volumes:
      - nats_data:/data
    networks:
      - memgos-network
    healthcheck:
      test: ["CMD", "nats", "server", "check", "--server=nats://localhost:4222"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Qdrant for vector database (if needed)
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: memgos-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - memgos-network

networks:
  memgos-network:
    driver: bridge

volumes:
  nats_data:
  qdrant_data: